services:
  mongo:
    container_name: mongo
    image: mongo:latest
      #    environment:
      #      - MONGO_INITDB_ROOT_USERNAME=mehmet
      #      - MONGO_INITDB_ROOT_PASSWORD=mehmet
      # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      # Here you are setting the username and password
    # so change it to whatever you want
    # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db
