services:
  mongo:
    container_name: mongo
    image: mongo:latest
      #    environment:
      #      - MONGO_INITDB_ROOT_USERNAME=mehmet
      #      - MONGO_INITDB_ROOT_PASSWORD=mehmet
      # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      # Here you are setting the username and password
    # so change it to whatever you want
    # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'order-service'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

