spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123456
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path:  /h2-console
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  data:
    rest:
      basePath: /api/v1